<?php

namespace afijos\MainBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ParroquiaController__JMSInjector
{
    public static function inject($container) {
        $instance = new \afijos\MainBundle\Controller\ParroquiaController();
        return $instance;
    }
}
