security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_ADMINAF, ROLE_ASISTAF, ROLE_JEFE]
        ROLE_ADMINAF: [ROLE_USER, ROLE_ASISTAF, ROLE_JEFE]
        ROLE_ASISTAF: ROLE_USER
        ROLE_JEFE: ROLE_USER
    providers:
        usuarios:
            entity: {class : afijos\MainBundle\Entity\Usuario, property: username}

    firewalls:
        frontend:
            pattern: ^/*
            anonymous: ~
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check
                default_target_path: usuario_index
                always_use_default_target_path: true
            logout:
                path: usuario_logout
                target: usuario_login
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admaf, roles: ROLE_ADMINAF }
        - { path: ^/astaf, roles: ROLE_ASISTAF }
        - { path: ^/jf, roles: ROLE_JEFE }
        - { path: ^/index, roles: ROLE_USER }

    encoders:
        afijos\MainBundle\Entity\Usuario: plaintext