security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_DIRECTIVO, ROLE_EMPADMIN, ROLE_EMPOPER]
        ROLE_DIRECTIVO: [ROLE_USER, ROLE_EMPADMIN, ROLE_EMPOPER]
        ROLE_EMPADMIN: [ROLE_USER, ROLE_EMPOPER]
        ROLE_EMPOPER: ROLE_USER
    providers:
        usuarios:
            entity: {class : afijos\MainBundle\Entity\Usuario, property: username}

    firewalls:
        frontend:
            pattern: ^/*
            anonymous: ~
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check
                default_target_path: usuario_index
                always_use_default_target_path: true
            logout:
                path: usuario_logout
                target: usuario_login
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/directivo, roles: ROLE_DIRECTIVO }
        - { path: ^/empadmin, roles: ROLE_EMPADMIN }
        - { path: ^/index, roles: ROLE_USER }

    encoders:
        afijos\MainBundle\Entity\Usuario: plaintext