lsubestacion:
    pattern:  /
    defaults: { _controller: MainBundle:LSubestacion:index }
    
lsubestacion_new:
    pattern:  /new
    defaults: { _controller: MainBundle:LSubestacion:new }

lsubestacion_show:
    pattern:  /{id}/show
    defaults: { _controller: MainBundle:LSubestacion:show }

lsubestacion_create:
    pattern:  /create
    defaults: { _controller: MainBundle:LSubestacion:create }

lsubestacion_edit:
    pattern:  /{id}/edit
    defaults: { _controller: MainBundle:LSubestacion:edit }

lsubestacion_update:
    pattern:  /{id}/update
    defaults: { _controller: MainBundle:LSubestacion:update }

lsubestacion_delete:
    pattern:  /{id}/delete
    defaults: { _controller: MainBundle:LSubestacion:delete }
    
lsubestacion_eliminar:
    pattern:  /{id}/eliminar
    defaults: { _controller: MainBundle:LSubestacion:eliminar }
    
buscar_lsubestacion:
    pattern:  /buscar-lsubestacion
    defaults: { _controller: MainBundle:LSubestacion:buscarLSubestacion}
    
lsubestacion_listar:
    pattern:  /listar-lsubestacion
    defaults: { _controller: MainBundle:LSubestacion:listarLSubestacion }
    
lsubestacion_rformulario:
    pattern:  /rformulario
    defaults: { _controller: MainBundle:LSubestacion:rformulario }

lsubestacion_reporte:
    pattern:  /reporte
    defaults: { _controller: MainBundle:LSubestacion:reporte }

lsubestacion_depreciar:
    pattern:  /{id}/depreciar
    defaults: { _controller: MainBundle:LSubestacion:depreciar }
    
lsubestacion_edepreciar:
    pattern:  /{id}/edepreciar
    defaults: { _controller: MainBundle:LSubestacion:edepreciar }
    
lsubestacion_ubicar:
    pattern:  /{id}/ubicar
    defaults: { _controller: MainBundle:LSubestacion:ubicar }
    
lsubestacion_ubicarform:
    pattern:  /ubicarform
    defaults: { _controller: MainBundle:LSubestacion:ubicarform }
    
lsubestacion_historialdeprec:
    pattern:  /{id}/historialdeprec
    defaults: { _controller: MainBundle:LSubestacion:historialdeprec }