<?php

namespace Proxies\__CG__\afijos\MainBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Bajas extends \afijos\MainBundle\Entity\Bajas implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'afijos\\MainBundle\\Entity\\Bajas' . "\0" . 'id', '' . "\0" . 'afijos\\MainBundle\\Entity\\Bajas' . "\0" . 'descripcion', '' . "\0" . 'afijos\\MainBundle\\Entity\\Bajas' . "\0" . 'detalle', '' . "\0" . 'afijos\\MainBundle\\Entity\\Bajas' . "\0" . 'estado', '' . "\0" . 'afijos\\MainBundle\\Entity\\Bajas' . "\0" . 'fechaSolicitada', '' . "\0" . 'afijos\\MainBundle\\Entity\\Bajas' . "\0" . 'fechaAprobado', '' . "\0" . 'afijos\\MainBundle\\Entity\\Bajas' . "\0" . 'bienesCustodio');
        }

        return array('__isInitialized__', '' . "\0" . 'afijos\\MainBundle\\Entity\\Bajas' . "\0" . 'id', '' . "\0" . 'afijos\\MainBundle\\Entity\\Bajas' . "\0" . 'descripcion', '' . "\0" . 'afijos\\MainBundle\\Entity\\Bajas' . "\0" . 'detalle', '' . "\0" . 'afijos\\MainBundle\\Entity\\Bajas' . "\0" . 'estado', '' . "\0" . 'afijos\\MainBundle\\Entity\\Bajas' . "\0" . 'fechaSolicitada', '' . "\0" . 'afijos\\MainBundle\\Entity\\Bajas' . "\0" . 'fechaAprobado', '' . "\0" . 'afijos\\MainBundle\\Entity\\Bajas' . "\0" . 'bienesCustodio');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Bajas $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDetalle($detalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDetalle', array($detalle));

        return parent::setDetalle($detalle);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetalle', array());

        return parent::getDetalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaSolicitada($fechaSolicitada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaSolicitada', array($fechaSolicitada));

        return parent::setFechaSolicitada($fechaSolicitada);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaSolicitada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaSolicitada', array());

        return parent::getFechaSolicitada();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAprobado($fechaAprobado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAprobado', array($fechaAprobado));

        return parent::setFechaAprobado($fechaAprobado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAprobado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAprobado', array());

        return parent::getFechaAprobado();
    }

    /**
     * {@inheritDoc}
     */
    public function setBienesCustodio(\afijos\MainBundle\Entity\BienesCustodio $bienesCustodio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBienesCustodio', array($bienesCustodio));

        return parent::setBienesCustodio($bienesCustodio);
    }

    /**
     * {@inheritDoc}
     */
    public function getBienesCustodio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBienesCustodio', array());

        return parent::getBienesCustodio();
    }

}
