<?php

namespace Proxies\__CG__\afijos\MainBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DetalleDepreciacion extends \afijos\MainBundle\Entity\DetalleDepreciacion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'afijos\\MainBundle\\Entity\\DetalleDepreciacion' . "\0" . 'id', '' . "\0" . 'afijos\\MainBundle\\Entity\\DetalleDepreciacion' . "\0" . 'deprecAcumulada', '' . "\0" . 'afijos\\MainBundle\\Entity\\DetalleDepreciacion' . "\0" . 'deprecMensual', '' . "\0" . 'afijos\\MainBundle\\Entity\\DetalleDepreciacion' . "\0" . 'fechaDepreciacion', '' . "\0" . 'afijos\\MainBundle\\Entity\\DetalleDepreciacion' . "\0" . 'mesDepreciacion', '' . "\0" . 'afijos\\MainBundle\\Entity\\DetalleDepreciacion' . "\0" . 'bienesCustodio');
        }

        return array('__isInitialized__', '' . "\0" . 'afijos\\MainBundle\\Entity\\DetalleDepreciacion' . "\0" . 'id', '' . "\0" . 'afijos\\MainBundle\\Entity\\DetalleDepreciacion' . "\0" . 'deprecAcumulada', '' . "\0" . 'afijos\\MainBundle\\Entity\\DetalleDepreciacion' . "\0" . 'deprecMensual', '' . "\0" . 'afijos\\MainBundle\\Entity\\DetalleDepreciacion' . "\0" . 'fechaDepreciacion', '' . "\0" . 'afijos\\MainBundle\\Entity\\DetalleDepreciacion' . "\0" . 'mesDepreciacion', '' . "\0" . 'afijos\\MainBundle\\Entity\\DetalleDepreciacion' . "\0" . 'bienesCustodio');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DetalleDepreciacion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeprecAcumulada($deprecAcumulada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeprecAcumulada', array($deprecAcumulada));

        return parent::setDeprecAcumulada($deprecAcumulada);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeprecAcumulada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeprecAcumulada', array());

        return parent::getDeprecAcumulada();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeprecMensual($deprecMensual)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeprecMensual', array($deprecMensual));

        return parent::setDeprecMensual($deprecMensual);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeprecMensual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeprecMensual', array());

        return parent::getDeprecMensual();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaDepreciacion($fechaDepreciacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaDepreciacion', array($fechaDepreciacion));

        return parent::setFechaDepreciacion($fechaDepreciacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaDepreciacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaDepreciacion', array());

        return parent::getFechaDepreciacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setMesDepreciacion($mesDepreciacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMesDepreciacion', array($mesDepreciacion));

        return parent::setMesDepreciacion($mesDepreciacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getMesDepreciacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMesDepreciacion', array());

        return parent::getMesDepreciacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setBienesCustodio(\afijos\MainBundle\Entity\BienesCustodio $bienesCustodio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBienesCustodio', array($bienesCustodio));

        return parent::setBienesCustodio($bienesCustodio);
    }

    /**
     * {@inheritDoc}
     */
    public function getBienesCustodio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBienesCustodio', array());

        return parent::getBienesCustodio();
    }

}
